-- CREATE  SEQUENCE seq_sec_user_role_id;
INSERT INTO SECURITY_USER_ROLE (ROLE_TYPE) VALUES('ADMIN');
INSERT INTO SECURITY_USER_ROLE (ROLE_TYPE) VALUES('USER');
INSERT INTO SECURITY_USER_ROLE (ROLE_TYPE) VALUES('DEVELOPER');
INSERT INTO SECURITY_USER_ROLE (ROLE_TYPE) VALUES('TEST');


-- COMMIT;